CREATE SPFILE FROM PFILE;
SHUT IMMEDIATE;
STARTUP NOMOUNT;
SHOW PARAMETER NAME;
ALTER SYSTEM SET DB_UNIQUE_NAME='orap' SCOPE=SPFILE; 
ALTER SYSTEM RESET DB_RECOVERY_FILE_DEST SCOPE=SPFILE;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_1=
'LOCATION=/dbd/oradata/ora/arch1/
VALID_FOR=(ALL_LOGFILES,ALL_ROLES)
DB_UNIQUE_NAME=orap' scope=spfile;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
SHOW PARAMETER NAME;

ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ARCHIVE LOG LIST;
ALTER DATABASE FORCE LOGGING;
ALTER SYSTEM SET LOCAL_LISTENER='db1:1522';
ALTER SYSTEM SET LOG_ARCHIVE_MAX_PROCESSES=30;
ALTER SYSTEM SET LOG_ARCHIVE_FORMAT='ora_%t_%s_%r.arc' SCOPE=SPFILE; 
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 10G SCOPE=BOTH;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST = '/dbd/oradata/ora/fra/'  SCOPE=BOTH;
ALTER SYSTEM SET DB_FLASHBACK_RETENTION_TARGET = 60 SCOPE=BOTH;
ALTER DATABASE FLASHBACK ON;
ALTER SYSTEM SET REMOTE_LOGIN_PASSWORDFILE=EXCLUSIVE SCOPE=SPFILE;
SHUTDOWN IMMEDIATE;
STARTUP;
CREATE PFILE FROM SPFILE;
