ALTER DATABASE CREATE STANDBY CONTROLFILE AS '/dbd/oradata/ora/control_standby.ctl';
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;

SHOW PARAMETER NAME;
SELECT MEMBER FROM V$LOGFILE;
ALTER DATABASE ADD STANDBY LOGFILE THREAD 1 GROUP 4 ('/dbd/oradata/ora/redo04.log') SIZE 200M; 
ALTER DATABASE ADD STANDBY LOGFILE THREAD 1 GROUP 5 ('/dbd/oradata/ora/redo05.log') SIZE 200M; 
ALTER DATABASE ADD STANDBY LOGFILE THREAD 1 GROUP 6 ('/dbd/oradata/ora/redo06.log') SIZE 200M; 
ALTER DATABASE ADD STANDBY LOGFILE THREAD 1 GROUP 7 ('/dbd/oradata/ora/redo07.log') SIZE 200M; 
select thread#, group#, sequence#, status, bytes from v$standby_log;
SELECT MEMBER FROM V$LOGFILE ORDER BY GROUP#;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_1=
'LOCATION=/dbd/oradata/ora/arch1/
VALID_FOR=(ALL_LOGFILES,ALL_ROLES)
DB_UNIQUE_NAME=oras' scope=spfile;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_2=
'SERVICE=orap LGWR ASYNC
VALID_FOR=(ALL_LOGFILES,PRIMARY_ROLE)
DB_UNIQUE_NAME=orap' SCOPE=SPFILE;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_1=ENABLE;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_2=ENABLE;
ALTER SYSTEM SET LOG_ARCHIVE_MAX_PROCESSES=30;
ALTER SYSTEM SET LOG_ARCHIVE_FORMAT='ora_%t_%s_%r.arc' SCOPE=SPFILE;
ALTER SYSTEM SET REMOTE_LOGIN_PASSWORDFILE=EXCLUSIVE SCOPE=SPFILE;

ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(oras,orap)';
ALTER SYSTEM SET FAL_CLIENT='oras';
ALTER SYSTEM SET FAL_SERVER='orap';
ALTER SYSTEM SET LOCAL_LISTENER='db2:1522';

ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT=AUTO;
ALTER DATABASE SET STANDBY DATABASE TO MAXIMIZE PERFORMANCE;
ALTER DATABASE FLASHBACK ON;
SHUTDOWN IMMEDIATE;
STARTUP;
CREATE PFILE FROM SPFILE;

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;

ALTER SESSION SET nls_date_format='DD-MON-YYYY HH24:MI:SS';
SELECT SEQUENCE#, FIRST_TIME, NEXT_TIME, APPLIED   FROM V$ARCHIVED_LOG ORDER BY SEQUENCE#;
SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;
